"""
decrypt_now.py  —  Full AES-256-GCM decryption of CinemaOS provider API
=========================================================================
Reverse-engineered from js_full_1386.js module 91712.

Algorithm (from JS source):
  - Encryption key: ENCRYPTION_KEY env var OR hardcoded fallback
    "a1b2c3d4e4f6477658455678901477567890abcdef1234567890abcdef123456"
  - Response JSON structure: {data: {encrypted, cin, mao}} OR
    {encrypted: "...", data: {encrypted, cin, mao}}
  - encrypted = ciphertext (hex)
  - cin       = IV (hex, 16 bytes)
  - mao       = auth tag (hex, 16 bytes)
  - Key derivation: if version >= 1 → PBKDF2(key, salt, 100000, 32, sha256)
                    if legacy (no salt) → sha256(IV)[:32]
  - Cipher: AES-256-GCM

Run:  pip install pycryptodome requests
      python decrypt_now.py
"""

import re, json, hashlib, requests
from Crypto.Cipher import AES

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0",
    "Referer":    "https://cinemaos.tech/",
    "Origin":     "https://cinemaos.tech",
    "Accept":     "application/json, */*",
}

# ── Hardcoded ENCRYPTION_KEY from JS source ───────────────────────────────
ENCRYPTION_KEY_HEX = "a1b2c3d4e4f6477658455678901477567890abcdef1234567890abcdef123456"
# Also try the second hardcoded key found in the JS
ENCRYPTION_KEY_HEX_2 = "a7f3b9c2e8d4f1a6b5c9e2d7f4a8b3c6e1d9f7a4b2c8e5d3f9a6b4c1e7d2f8a5"

# ── Known _rk (hardcoded in JS) ───────────────────────────────────────────
RK_HARDCODED = "2549b22d9bf0d91847a2811baac98d0079e02dba592aea94"

SEP = "=" * 70


def decrypt_aes_gcm(encrypted_hex, cin_hex, mao_hex, key_hex,
                    salt_hex=None, use_pbkdf2=False):
    """
    Decrypt AES-256-GCM.
    encrypted = ciphertext hex
    cin       = IV hex (16 bytes)
    mao       = auth tag hex (16 bytes)
    key_hex   = 32-byte hex key
    salt_hex  = optional salt for PBKDF2
    """
    try:
        ciphertext = bytes.fromhex(encrypted_hex)
        iv         = bytes.fromhex(cin_hex)
        auth_tag   = bytes.fromhex(mao_hex)
        key_raw    = bytes.fromhex(key_hex)

        if use_pbkdf2 and salt_hex:
            salt = bytes.fromhex(salt_hex)
            key_raw = hashlib.pbkdf2_hmac('sha256', key_raw, salt, 100000, 32)
        elif not salt_hex:
            # Legacy: key = sha256(IV)[:32]
            key_raw = hashlib.sha256(iv).digest()[:32]

        cipher = AES.new(key_raw, AES.MODE_GCM, nonce=iv)
        cipher.update(b"")
        plaintext = cipher.decrypt_and_verify(ciphertext, auth_tag)
        return plaintext.decode("utf-8")
    except Exception as e:
        return None


def find_generateContentHash():
    """Extract the generateContentHash function from the JS."""
    try:
        with open(r'c:\Users\AC\Desktop\Network analyser to find direct pai\js_full_1386.js',
                  encoding='utf-8', errors='ignore') as f:
            js = f.read()

        idx = js.find('generateContentHash')
        if idx == -1:
            return None
        snippet = js[idx:idx+2000]
        print(f"  [generateContentHash] Found at offset {idx}")
        print(f"  Snippet: {snippet[:600]}")
        return snippet
    except Exception as e:
        print(f"  [!] {e}")
        return None


def call_provider_api(tmdb_id, imdb_id, title, year, secret, rk,
                      content_type="movie", season=None, episode=None):
    params = {
        "type":    content_type,
        "tmdbId":  tmdb_id,
        "imdbId":  imdb_id,
        "t":       title,
        "ry":      year,
        "secret":  secret,
        "_rk":     rk,
    }
    if season:  params["season"]  = season
    if episode: params["episode"] = episode

    url = "https://cinemaos.tech/api/providerv4"
    print(f"  [API] GET {url}")
    r = requests.get(url, params=params, headers=HEADERS, timeout=15)
    print(f"  [API] HTTP {r.status_code}  {len(r.content)} bytes")
    return r


def main():
    print(f"\n{SEP}")
    print("  CinemaOS AES-256-GCM Decryptor")
    print(SEP)

    # Step 1: Find generateContentHash
    print("\n[1] Extracting generateContentHash function...")
    find_generateContentHash()

    # Step 2: Call live API with hardcoded _rk
    print(f"\n[2] Calling provider API...")
    print(f"  Using hardcoded _rk: {RK_HARDCODED}")
    print(f"  Need to find secret = generateContentHash(tmdbId, imdbId, ...)")

    # The secret is generated by generateContentHash — we need to find that function
    # For now use the known secret from the previous scan
    known_secret = "d4475c101f7236651d09c6ec4f52e1c84b1bfac087dd537aa0f2850d97224729"

    r = call_provider_api("1318447", "tt16431404", "Apex", "2026",
                          known_secret, RK_HARDCODED)

    if r.status_code != 200:
        print(f"  [!] API returned {r.status_code}: {r.text[:200]}")
        return

    try:
        resp = r.json()
    except Exception:
        print(f"  [!] Not JSON: {r.text[:200]}")
        return

    print(f"  Response keys: {list(resp.keys())}")

    # Step 3: Extract encrypted fields
    # The JS expects: {encrypted, cin, mao} — but the API returns {data: {encrypted: "hex..."}}
    # The outer structure has "encrypted" and "data" keys
    # Looking at the JS: x.encrypted && x.data → this.decryptResponse(x.data)
    # So x.data is the object with {encrypted, cin, mao}

    data_obj = resp.get("data", {})
    print(f"  data keys: {list(data_obj.keys()) if isinstance(data_obj, dict) else type(data_obj)}")

    if isinstance(data_obj, dict):
        encrypted_hex = data_obj.get("encrypted", "")
        cin_hex       = data_obj.get("cin", "")
        mao_hex       = data_obj.get("mao", "")
        salt_hex      = data_obj.get("salt", "")
        version       = data_obj.get("version", 0)
        print(f"  encrypted: {len(encrypted_hex)} chars")
        print(f"  cin (IV):  {cin_hex[:32]}... ({len(cin_hex)//2} bytes)")
        print(f"  mao (tag): {mao_hex[:32]}... ({len(mao_hex)//2} bytes)")
        print(f"  salt:      {salt_hex[:32] if salt_hex else 'none'}")
        print(f"  version:   {version}")
    elif isinstance(data_obj, str):
        # The "encrypted" field is the whole hex blob — legacy format
        # Need to split: first 32 hex = IV (16 bytes), last 32 hex = auth tag (16 bytes)
        encrypted_hex = data_obj
        print(f"  data is a hex string: {len(encrypted_hex)} chars")
        # Try to split: IV(16B) + ciphertext + tag(16B)
        if len(encrypted_hex) >= 64:
            cin_hex = encrypted_hex[:32]
            mao_hex = encrypted_hex[-32:]
            encrypted_hex = encrypted_hex[32:-32]
            salt_hex = ""
            version = 0
            print(f"  Assumed split: IV={cin_hex}  tag={mao_hex}")
            print(f"  Ciphertext: {len(encrypted_hex)//2} bytes")
        else:
            print("  [!] Data too short to split")
            return
    else:
        print(f"  [!] Unexpected data type: {type(data_obj)}")
        return

    # Step 4: Decrypt
    print(f"\n[3] Attempting AES-256-GCM decryption...")

    key_candidates = [
        ENCRYPTION_KEY_HEX,
        ENCRYPTION_KEY_HEX_2,
        "d3f8a5b2c9e6d1f7a4b8c5e2d9f3a6b1c7e4d8f2a9b5c3e7d4f1a8b6c2e9d5f3",
    ]

    for key_hex in key_candidates:
        print(f"\n  Trying key: {key_hex[:32]}...")

        # Mode 1: Direct key (legacy, version < 1)
        result = decrypt_aes_gcm(encrypted_hex, cin_hex, mao_hex, key_hex,
                                  salt_hex=None, use_pbkdf2=False)
        if result:
            print(f"\n  [★ DECRYPTED — direct key]")
            print(f"  Plaintext ({len(result)} chars):")
            print(result[:1000])
            save_result(result)
            return

        # Mode 2: PBKDF2 with salt (version >= 1)
        if salt_hex:
            result = decrypt_aes_gcm(encrypted_hex, cin_hex, mao_hex, key_hex,
                                      salt_hex=salt_hex, use_pbkdf2=True)
            if result:
                print(f"\n  [★ DECRYPTED — PBKDF2 with salt]")
                print(f"  Plaintext ({len(result)} chars):")
                print(result[:1000])
                save_result(result)
                return

        # Mode 3: Legacy — key = sha256(IV)[:32]
        result = decrypt_aes_gcm(encrypted_hex, cin_hex, mao_hex, key_hex,
                                  salt_hex="", use_pbkdf2=False)
        if result:
            print(f"\n  [★ DECRYPTED — legacy sha256(IV) key]")
            print(f"  Plaintext ({len(result)} chars):")
            print(result[:1000])
            save_result(result)
            return

    print("\n  [!] Decryption failed with all key candidates")
    print(f"  The ENCRYPTION_KEY is set server-side via environment variable")
    print(f"  Fallback key in JS: {ENCRYPTION_KEY_HEX}")
    print(f"  This means the server overrides it — need to capture via v5.0 analyser")


def save_result(plaintext):
    out = r'c:\Users\AC\Desktop\Network analyser to find direct pai\decrypted_payload.json'
    with open(out, 'w', encoding='utf-8') as f:
        f.write(plaintext)
    print(f"\n  [saved] {out}")

    # Extract stream URLs
    urls = re.findall(r'https?://[^\s"\'<>\\]+\.m3u8[^\s"\'<>\\]*', plaintext)
    stream_urls = re.findall(r'https?://[^\s"\'<>\\]+/stream/[^\s"\'<>\\]*', plaintext)
    all_urls = list(dict.fromkeys(urls + stream_urls))
    if all_urls:
        print(f"\n  [★ STREAM URLS FOUND]:")
        for u in all_urls:
            print(f"    {u}")


if __name__ == "__main__":
    main()
