"""
direct_api_client.py  —  CinemaOS Direct Stream Client
========================================================
Auto-generated by extract_api.py
Generated: 2026-05-23 08:27:46

Usage:
  pip install requests pycryptodome
  python direct_api_client.py
"""

import requests, re, json, hashlib, time

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0",
    "Referer":    "https://cinemaos.tech/",
    "Origin":     "https://cinemaos.tech",
}

# ── SUBTITLE API (open, no auth) ─────────────────────────────────────
def get_subtitles(tmdb_id, content_type="movie", season=None, episode=None):
    if content_type == "movie":
        url = f"https://sub.vdrk.site/v1/movie/{tmdb_id}"
    else:
        url = f"https://sub.vdrk.site/v1/tv/{tmdb_id}/{season}/{episode}"
    r = requests.get(url, headers=HEADERS, timeout=10)
    return r.json() if r.status_code == 200 else []

# ── KNOWN LIVE STREAM URLS (from previous scan) ─────────────────────
# NOTE: These stream hashes expire — re-run extract_api.py to get fresh ones
# https://storrrrrrm.site/stream/d42f649481170d33/master.m3u8
# https://storrrrrrm.site/stream/d42f649481170d33/1080p.m3u8
# https://storrrrrrm.site/stream/d42f649481170d33/720p.m3u8

MASTER_M3U8 = "https://storrrrrrm.site/stream/d42f649481170d33/master.m3u8"

def get_stream_direct():
    """Fetch the known stream URL directly."""
    r = requests.get(MASTER_M3U8, headers=HEADERS, timeout=15)
    if r.status_code == 200 and "#EXTM3U" in r.text:
        print("Stream is LIVE:")
        print(r.text[:500])
        return r.text
    else:
        print(f"Stream expired (HTTP {r.status_code}) — need fresh tokens")
        return None

# ── PROVIDER API (requires fresh secret + _rk tokens) ───────────────
# The tokens are generated by the site JS — use the network analyser
# with v5.0 to capture fresh tokens automatically.

PROVIDER_API = "https://cinemaos.tech/api/providerv4"

# Last captured tokens (from scan 2026-05-23):
LAST_SECRET = "d4475c101f7236651d09c6ec4f52e1c84b1bfac087dd537aa0f2850d97224729"
LAST_RK     = "2549b22d9bf0d91847a2811baac98d0079e02dba592aea94"

def call_provider(tmdb_id, imdb_id, title, year, secret, rk,
                  content_type="movie", season=None, episode=None):
    params = {
        "type":   content_type,
        "tmdbId": tmdb_id,
        "imdbId": imdb_id,
        "t":      title,
        "ry":     year,
        "secret": secret,
        "_rk":    rk,
    }
    if season:  params["season"]  = season
    if episode: params["episode"] = episode
    r = requests.get(PROVIDER_API, params=params, headers=HEADERS, timeout=15)
    print(f"Provider API: HTTP {r.status_code}  {len(r.content)} bytes")
    return r

# ── MAIN ─────────────────────────────────────────────────────────────
if __name__ == "__main__":
    tmdb_id = "1318447"
    imdb_id = "tt16431404"
    title   = "Apex"
    year    = "2026"

    print("=== CinemaOS Direct API Client ===")
    print()

    # 1. Get subtitles (always works, no auth)
    print("[1] Fetching subtitles...")
    subs = get_subtitles(tmdb_id)
    for s in subs:
        print(f"  Subtitle: {s}")

    # 2. Test known stream URL
    print()
    print("[2] Testing known stream URL...")
    get_stream_direct()

    # 3. Call provider API with last known tokens
    print()
    print("[3] Calling provider API with last known tokens...")
    print("    (tokens may be expired — use v5.0 analyser for fresh ones)")
    r = call_provider(tmdb_id, imdb_id, title, year, LAST_SECRET, LAST_RK)
    try:
        data = r.json()
        enc = data.get("data", {}).get("encrypted", "")
        if enc:
            print(f"  Encrypted response: {len(enc)} chars")
            print(f"  First 80: {enc[:80]}")
            print()
            print("  To decrypt: run extract_api.py with pycryptodome installed")
    except Exception as e:
        print(f"  Response: {r.text[:300]}")